// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOL0UCJSl7ixz_5t9C3anmdp9bEGOthWw',
    appId: '1:376467446540:web:6e54cada2dbea493f8c729',
    messagingSenderId: '376467446540',
    projectId: 'mychatapp-5c372',
    authDomain: 'mychatapp-5c372.firebaseapp.com',
    storageBucket: 'mychatapp-5c372.appspot.com',
    measurementId: 'G-YVY3P3354C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCKoWzmOSC33qC3tJn_ADkChzizvfkM3Y',
    appId: '1:376467446540:android:426eb59029a2aa33f8c729',
    messagingSenderId: '376467446540',
    projectId: 'mychatapp-5c372',
    storageBucket: 'mychatapp-5c372.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7LdNVQQ2yyMieeMScIvhyj-O8RhVxmWk',
    appId: '1:376467446540:ios:138c6c187917c8b4f8c729',
    messagingSenderId: '376467446540',
    projectId: 'mychatapp-5c372',
    storageBucket: 'mychatapp-5c372.appspot.com',
    iosBundleId: 'com.example.chatAppFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7LdNVQQ2yyMieeMScIvhyj-O8RhVxmWk',
    appId: '1:376467446540:ios:96c92b8a53af8e7bf8c729',
    messagingSenderId: '376467446540',
    projectId: 'mychatapp-5c372',
    storageBucket: 'mychatapp-5c372.appspot.com',
    iosBundleId: 'com.example.chatAppFb.RunnerTests',
  );
}
